spring.application.name=tripo

# Tudo em uma única linha (usuario:senha@host:porta/banco)
spring.mongodb.uri=mongodb://root:example@localhost:27017/tripodb?authSource=admin

spring.data.mongodb.auto-index-creation=true