spring.application.name=tripo
spring.mongodb.port=27017
spring.mongodb.host=localhost
spring.mongodb.database=tripodb
spring.mongodb.password=admin
spring.mongodb.username=admin
spring.data.mongodb.auto-index-creation=true